pub fn to_return_suffix(ty: &str) -> ~str {
    match ty {
        "void" | "VOID" | "GLvoid" => ~"",
        ty_str => ~" -> " + ty_str.to_owned(),
    }
}

/// Converts a C style type definition to the Rust equivalent
pub fn to_rust_ty(ty: &str) -> ~str {
    match ty {
        // gl.xml types
        "GLDEBUGPROC"               => ~"GLDEBUGPROC",
        "GLDEBUGPROCAMD"            => ~"GLDEBUGPROCAMD",
        "GLDEBUGPROCARB"            => ~"GLDEBUGPROCARB",
        "GLDEBUGPROCKHR"            => ~"GLDEBUGPROCKHR",
        "GLbitfield"                => ~"GLbitfield",
        "GLboolean"                 => ~"GLboolean",
        "GLbyte"                    => ~"GLbyte",
        "GLclampd"                  => ~"GLclampd",
        "GLclampf"                  => ~"GLclampf",
        "GLclampx"                  => ~"GLclampx",
        "GLdouble"                  => ~"GLdouble",
        "GLeglImageOES"             => ~"GLeglImageOES",
        "GLenum"                    => ~"GLenum",
        "GLfixed"                   => ~"GLfixed",
        "GLfloat"                   => ~"GLfloat",
        "GLhalfNV"                  => ~"GLhalfNV",
        "GLhandleARB"               => ~"GLhandleARB",
        "GLint"                     => ~"GLint",
        "GLint64EXT"                => ~"GLint64EXT",
        "GLintptr"                  => ~"GLintptr",
        "GLintptrARB"               => ~"GLintptrARB",
        "GLshort"                   => ~"GLshort",
        "GLsizei"                   => ~"GLsizei",
        "GLsizeiptr"                => ~"GLsizeiptr",
        "GLsizeiptrARB"             => ~"GLsizeiptrARB",
        "GLsync"                    => ~"GLsync",
        "GLubyte"                   => ~"GLubyte",
        "GLuint"                    => ~"GLuint",
        "GLuint64"                  => ~"GLuint64",
        "GLuint64EXT"               => ~"GLuint64EXT",
        "GLushort"                  => ~"GLushort",
        "GLvdpauSurfaceNV"          => ~"GLvdpauSurfaceNV",
        "void "                     => ~"c_void",
        "GLboolean *"               => ~"*GLboolean",
        "GLchar *"                  => ~"*GLchar",
        "GLcharARB *"               => ~"*GLcharARB",
        "GLdouble *"                => ~"*GLdouble",
        "GLenum *"                  => ~"*GLenum",
        "GLfixed *"                 => ~"*GLfixed",
        "GLfloat *"                 => ~"*GLfloat",
        "GLhandleARB *"             => ~"*GLhandleARB",
        "GLint *"                   => ~"*GLint",
        "GLint64 *"                 => ~"*GLint64",
        "GLint64EXT *"              => ~"*GLint64EXT",
        "GLsizei *"                 => ~"*GLsizei",
        "GLubyte *"                 => ~"*GLubyte",
        "GLuint *"                  => ~"*GLuint",
        "GLuint64 *"                => ~"*GLuint64",
        "GLuint64EXT *"             => ~"*GLuint64EXT",
        "GLushort *"                => ~"*GLushort",
        "GLvoid *"                  => ~"*GLvoid",
        "GLvoid **"                 => ~"**GLvoid",
        "const GLboolean *"         => ~"*GLboolean",
        "const GLbyte *"            => ~"*GLbyte",
        "const GLchar *"            => ~"*GLchar",
        "const GLcharARB *"         => ~"*GLcharARB",
        "const GLclampf *"          => ~"*GLclampf",
        "const GLdouble *"          => ~"*GLdouble",
        "const GLenum *"            => ~"*GLenum",
        "const GLfixed *"           => ~"*GLfixed",
        "const GLfloat *"           => ~"*GLfloat",
        "const GLhalfNV *"          => ~"*GLhalfNV",
        "const GLint *"             => ~"*GLint",
        "const GLint64EXT *"        => ~"*GLint64EXT",
        "const GLintptr *"          => ~"*GLintptr",
        "const GLshort *"           => ~"*GLshort",
        "const GLsizei *"           => ~"*GLsizei",
        "const GLsizeiptr *"        => ~"*GLsizeiptr",
        "const GLubyte *"           => ~"*GLubyte",
        "const GLuint *"            => ~"*GLuint",
        "const GLuint64 *"          => ~"*GLuint64",
        "const GLuint64EXT *"       => ~"*GLuint64EXT",
        "const GLushort *"          => ~"*GLushort",
        "const GLvdpauSurfaceNV *"  => ~"*GLvdpauSurfaceNV",
        "const GLvoid *"            => ~"*GLvoid",
        "const void *"              => ~"*c_void",
        "void *"                    => ~"*c_void",
        "const GLboolean **"        => ~"**GLboolean",
        "const GLchar **"           => ~"**GLchar",
        "const GLcharARB **"        => ~"**GLcharARB",
        "const GLvoid **"           => ~"**GLvoid",
        "const GLchar *const*"      => ~"**GLchar",
        "const GLvoid *const*"      => ~"**GLvoid",
        "struct _cl_context *"      => ~"*_cl_context",
        "struct _cl_event *"        => ~"*_cl_event",

        // glx.xml types
        "Bool"                      => ~"Bool",
        "Colormap"                  => ~"Colormap",
        "DMbuffer"                  => ~"DMbuffer",
        "Font"                      => ~"Font",
        "GLXContext"                => ~"GLXContext",
        "GLXContextID"              => ~"GLXContextID",
        "GLXDrawable"               => ~"GLXDrawable",
        "GLXFBConfig"               => ~"GLXFBConfig",
        "GLXFBConfigSGIX"           => ~"GLXFBConfigSGIX",
        "GLXPbuffer"                => ~"GLXPbuffer",
        "GLXPbufferSGIX"            => ~"GLXPbufferSGIX",
        "GLXPixmap"                 => ~"GLXPixmap",
        "GLXVideoCaptureDeviceNV"   => ~"GLXVideoCaptureDeviceNV",
        "GLXVideoDeviceNV"          => ~"GLXVideoDeviceNV",
        "GLXVideoSourceSGIX"        => ~"GLXVideoSourceSGIX",
        "GLXWindow"                 => ~"GLXWindow",
        // "GLboolean"                 => ~"GLboolean",
        // "GLenum"                    => ~"GLenum",
        // "GLint"                     => ~"GLint",
        // "GLsizei"                   => ~"GLsizei",
        // "GLuint"                    => ~"GLuint",
        "Pixmap"                    => ~"Pixmap",
        "Status"                    => ~"Status",
        "VLNode"                    => ~"VLNode",
        "VLPath"                    => ~"VLPath",
        "VLServer"                  => ~"VLServer",
        "Window"                    => ~"Window",
        "__GLXextFuncPtr"           => ~"__GLXextFuncPtr",
        "const GLXContext"          => ~"const GLXContext",
        "float "                    => ~"c_float",
        "int "                      => ~"c_int",
        "int64_t"                   => ~"i64",
        "unsigned int "             => ~"c_uint",
        "unsigned long "            => ~"c_ulong",
        // "void "                     => ~"c_void",
        "DMparams *"                => ~"*DMparams",
        "Display *"                 => ~"*Display",
        "GLXFBConfig *"             => ~"*GLXFBConfig",
        "GLXFBConfigSGIX *"         => ~"*GLXFBConfigSGIX",
        "GLXHyperpipeConfigSGIX *"  => ~"*GLXHyperpipeConfigSGIX",
        "GLXHyperpipeNetworkSGIX *" => ~"*GLXHyperpipeNetworkSGIX",
        "GLXVideoCaptureDeviceNV *" => ~"*GLXVideoCaptureDeviceNV",
        "GLXVideoDeviceNV *"        => ~"*GLXVideoDeviceNV",
        // "GLuint *"                  => ~"*GLuint",
        "XVisualInfo *"             => ~"*XVisualInfo",
        // "const GLubyte *"           => ~"*GLubyte",
        "const char *"              => ~"*c_char",
        "const int *"               => ~"*c_int",
        // "const void *"              => ~"*c_void",
        "int *"                     => ~"*c_int",
        "int32_t *"                 => ~"*i32",
        "int64_t *"                 => ~"*i64",
        "long *"                    => ~"*c_long",
        "unsigned int *"            => ~"*c_uint",
        "unsigned long *"           => ~"*c_ulong",
        // "void *"                    => ~"*c_void",

        // wgl.xml types
        "BOOL"                      => ~"BOOL",
        "DWORD"                     => ~"DWORD",
        "FLOAT"                     => ~"FLOAT",
        // "GLbitfield"                => ~"GLbitfield",
        // "GLboolean"                 => ~"GLboolean",
        // "GLenum"                    => ~"GLenum",
        // "GLfloat"                   => ~"GLfloat",
        // "GLint"                     => ~"GLint",
        // "GLsizei"                   => ~"GLsizei",
        // "GLuint"                    => ~"GLuint",
        // "GLushort"                  => ~"GLushort",
        "HANDLE"                    => ~"HANDLE",
        "HDC"                       => ~"HDC",
        "HENHMETAFILE"              => ~"HENHMETAFILE",
        "HGLRC"                     => ~"HGLRC",
        "HGPUNV"                    => ~"HGPUNV",
        "HPBUFFERARB"               => ~"HPBUFFERARB",
        "HPBUFFEREXT"               => ~"HPBUFFEREXT",
        "HPVIDEODEV"                => ~"HPVIDEODEV",
        "HVIDEOINPUTDEVICENV"       => ~"HVIDEOINPUTDEVICENV",
        "HVIDEOOUTPUTDEVICENV"      => ~"HVIDEOOUTPUTDEVICENV",
        "INT"                       => ~"INT",
        "INT64"                     => ~"INT64",
        "LPCSTR"                    => ~"LPCSTR",
        "LPGLYPHMETRICSFLOAT"       => ~"LPGLYPHMETRICSFLOAT",
        "LPVOID"                    => ~"LPVOID",
        "PGPU_DEVICE"               => ~"PGPU_DEVICE",
        "PROC"                      => ~"PROC",
        "UINT"                      => ~"UINT",
        "VOID"                      => ~"VOID",
        // "int "                      => ~"c_int",
        // "unsigned int "             => ~"c_uint",
        // "void "                     => ~"c_void",
        "BOOL *"                    => ~"*BOOL",
        "DWORD *"                   => ~"*DWORD",
        "FLOAT *"                   => ~"*FLOAT",
        // "GLuint *"                  => ~"*GLuint",
        "HANDLE *"                  => ~"*HANDLE",
        "HGPUNV *"                  => ~"*HGPUNV",
        "HPVIDEODEV *"              => ~"*HPVIDEODEV",
        "HVIDEOINPUTDEVICENV *"     => ~"*HVIDEOINPUTDEVICENV",
        "HVIDEOOUTPUTDEVICENV *"    => ~"*HVIDEOOUTPUTDEVICENV",
        "INT32 *"                   => ~"*INT32",
        "INT64 *"                   => ~"*INT64",
        "UINT *"                    => ~"*UINT",
        "USHORT *"                  => ~"*USHORT",
        "const COLORREF *"          => ~"*COLORREF",
        "const DWORD *"             => ~"*DWORD",
        "const FLOAT *"             => ~"*FLOAT",
        // "const GLushort *"          => ~"*GLushort",
        "const HANDLE *"            => ~"*HANDLE",
        "const HGPUNV *"            => ~"*HGPUNV",
        "const LAYERPLANEDESCRIPTOR *"  => ~"*LAYERPLANEDESCRIPTOR",
        "const LPVOID *"            => ~"*LPVOID",
        "const PIXELFORMATDESCRIPTOR *" => ~"*PIXELFORMATDESCRIPTOR",
        "const USHORT *"            => ~"*USHORT",
        // "const char *"              => ~"*c_char",
        // "const int *"               => ~"*c_int",
        "float *"                   => ~"*c_float",
        // "int *"                     => ~"*c_int",
        // "unsigned long *"           => ~"*c_ulong",
        // "void *"                    => ~"*c_void",

        // failure
        _ => fail!("Type conversion not implemented for `%s`", ty),
    }
}

pub type Src = &'static [&'static str];

pub static GL_ALIASES: Src = &[
    "// Common types from OpenGL 1.1",
    "pub type GLenum = c_uint;",
    "pub type GLboolean = c_uchar;",
    "pub type GLbitfield = c_uint;",
    "pub type GLbyte = c_schar;",
    "pub type GLshort = c_short;",
    "pub type GLint = c_int;",
    "pub type GLsizei = c_int;",
    "pub type GLubyte = c_uchar;",
    "pub type GLushort = c_ushort;",
    "pub type GLuint = c_uint;",
    "pub type GLhalf = c_ushort;",
    "pub type GLfloat = c_float;",
    "pub type GLclampf = c_float;",
    "pub type GLdouble = c_double;",
    "pub type GLclampd = c_double;",
    "pub type GLvoid = c_void;",
    "",
    "// GL type for program/shader text",
    "pub type GLchar = c_char;",
    "",
    "// GL types for handling large vertex buffer objects",
    "pub type GLintptr = ptrdiff_t;",
    "pub type GLsizeiptr = ptrdiff_t;",
    "",
    "// GL types for handling large vertex buffer objects",
    "pub type GLintptrARB = ptrdiff_t;",
    "pub type GLsizeiptrARB = ptrdiff_t;",
    "",
    "// GL types for program/shader text and shader object handles",
    "pub type GLcharARB = c_char;",
    "pub type GLhandleARB = c_uint;",
    "",
    "// GL type for \"half\" precision (s10e5) float data in host memory",
    "pub type GLhalfARB = c_ushort;",
    "pub type GLhalfNV = c_ushort;",
    "",
    "pub type GLint64EXT = i64;",
    "pub type GLuint64EXT = u64;",
    "pub type GLint64 = i64;",
    "pub type GLuint64 = u64;",
    "",
    "pub type GLsync = *c_void;",
    "",
    "// These incomplete types let us declare types compatible with OpenCL's cl_context and cl_event",
    "pub struct _cl_context;",
    "pub struct _cl_event;",
    "",
    "pub type GLDEBUGPROCARB = extern \"C\" fn(source: GLenum, gltype: GLenum, id: GLuint, severity: GLenum, length: GLsizei, message: *GLchar, userParam: *c_void);",
    "pub type GLDEBUGPROCKHR = extern \"C\" fn(source: GLenum, gltype: GLenum, id: GLuint, severity: GLenum, length: GLsizei, message: *GLchar, userParam: *c_void);",
    "pub type GLDEBUGPROCAMD = extern \"C\" fn(id: GLuint, category: GLenum, severity: GLenum, length: GLsizei, message: *GLchar, userParam: *c_void);",
    "pub type GLDEBUGPROC = extern \"C\" fn(source: GLenum, gltype: GLenum, id: GLuint, severity: GLenum, length: GLsizei, message: *GLchar, userParam: *c_void);",
    "",
    "pub type GLvdpauSurfaceNV = GLintptr;",
];

pub static X_ALIASES: Src = &[
    "pub type XID = c_ulong;",
    "pub type Bool = c_int;         // Not sure if this is correct...",
    "pub struct Display;",
];

pub static GLX_ALIASES: Src = &[
    "pub type GLXFBConfigID = XID;",
    "pub type GLXFBConfig = *c_void;",
    "pub type GLXContextID = XID;",
    "pub type GLXContext = *c_void;",
    "pub type GLXPixmap = XID;",
    "pub type GLXDrawable = XID;",
    "pub type GLXWindow = XID;",
    "pub type GLXPbuffer = XID;",
    "pub type __GLXextFuncPtr = extern \"C\" fn();",
    "pub type GLXVideoCaptureDeviceNV = XID;",
    "pub type GLXVideoDeviceNV = unsigned int;",
    "pub type GLXVideoSourceSGIX = XID;",
    "pub type GLXFBConfigIDSGIX = XID;",
    "pub type GLXFBConfigSGIX = *c_void;",
    "pub type GLXPbufferSGIX = XID;",
    "",
    "pub struct GLXPbufferClobberEvent {",
    "    event_type: c_int,          // GLX_DAMAGED or GLX_SAVED",
    "    draw_type: c_int,           // GLX_WINDOW or GLX_PBUFFER",
    "    serial: c_ulong,            // # of last request processed by server",
    "    send_event: Bool,           // true if this came for SendEvent request",
    "    display: *Display,          // display the event was read from",
    "    drawable: GLXDrawable,      // XID of Drawable",
    "    buffer_mask: c_uint,        // mask indicating which buffers are affected",
    "    aux_buffer: c_uint,         // which aux buffer was affected",
    "    x: c_int,",
    "    y: c_int,",
    "    width: c_int,",
    "    height: c_int,",
    "    count: c_int,               // if nonzero, at least this many more",
    "}",
    "",
    "pub struct GLXBufferSwapComplete {",
    "    type: c_int,",
    "    serial: c_ulong,            // # of last request processed by server",
    "    send_event: Bool,           // true if this came from a SendEvent request",
    "    display: *Display,          // Display the event was read from",
    "    drawable: GLXDrawable,      // drawable on which event was requested in event mask",
    "    event_type: c_int,",
    "    ust: i64,",
    "    msc: i64,",
    "    sbc: i64,",
    "}",
    "",
    "// typedef union __GLXEvent {",
    "//     GLXPbufferClobberEvent glxpbufferclobber;",
    "//     GLXBufferSwapComplete glxbufferswapcomplete;",
    "//     long pad[24];",
    "// } GLXEvent;",
    "",
    "pub struct GLXBufferClobberEventSGIX {",
    "    type: c_int,",
    "    serial: c_ulong,            // # of last request processed by server",
    "    send_event: Bool,           // true if this came for SendEvent request",
    "    display: *Display,          // display the event was read from",
    "    drawable: GLXDrawable,      // i.d. of Drawable",
    "    event_type: c_int,          // GLX_DAMAGED_SGIX or GLX_SAVED_SGIX",
    "    draw_type: c_int,           // GLX_WINDOW_SGIX or GLX_PBUFFER_SGIX",
    "    mask: c_uint,               // mask indicating which buffers are affected",
    "    x: c_int,",
    "    y: c_int,",
    "    width: c_int,",
    "    height: c_int,",
    "    count: c_int,               // if nonzero, at least this many more",
    "}",
    "",
    "pub struct GLXHyperpipeNetworkSGIX {",
    "    pipeName: [c_char, ..80],   // Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]",
    "    networkId: c_int,",
    "}",
    "",
    "pub struct GLXHyperpipeConfigSGIX {",
    "    pipeName: [c_char, ..80],   // Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]",
    "    channel: c_int,",
    "    participationType: c_uint,",
    "    timeSlice: c_int,",
    "}",
    "",
    "pub struct GLXPipeRect {",
    "    pipeName: [c_char, ..80],   // Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]",
    "    srcXOrigin: c_int,",
    "    srcYOrigin: c_int,",
    "    srcWidth: c_int,",
    "    srcHeight: c_int,",
    "    destXOrigin: c_int,",
    "    destYOrigin: c_int,",
    "    destWidth: c_int,",
    "    destHeight: c_int,",
    "}",
    "",
    "pub struct GLXPipeRectLimits {",
    "    pipeName: [c_char, ..80],   // Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]",
    "    XOrigin: c_int,",
    "    YOrigin: c_int,",
    "    maxHeight: c_int,",
    "    maxWidth: c_int,",
    "}",
];

pub static WIN_ALIASES: Src = &[
    "// From WinNT.h",
    "pub type CHAR = c_char;",
    "pub type HANDLE = PVOID;",
    "pub type LONG = c_long;",
    "pub type LPCSTR = *c_char;",
    "pub type VOID = c_void;",
    "",
    "// From Windef.h",
    "pub type BOOL = c_int;",
    "pub type BYTE = c_uchar;",
    "pub type COLORREF = DWORD;",
    "pub type FLOAT = c_float;",
    "pub type HDC = HANDLE;",
    "pub type HENHMETAFILE = HANDLE;",
    "pub type HGLRC = *c_void;",
    "pub type INT = c_int;",
    "pub type LPVOID = *c_void;",
    "pub type PROC = extern \"C\" fn();     // Not sure about this one :/",
    "pub struct RECT {",
    "    left: LONG,",
    "    top: LONG,",
    "    right: LONG,",
    "    bottom: LONG,",
    "}",
    "pub type UINT = c_uint;",
    "pub type USHORT = c_ushort;",
    "pub type WORD = c_ushort;",
    "",
    "// From BaseTsd.h",
    "pub type INT32 = i32;",
    "pub type INT64 = i64;",
    "",
    "// From IntSafe.h",
    "pub type DWORD = c_ulong;",
    "",
    "// From Wingdi.h",
    "pub struct POINTFLOAT {",
    "    x: FLOAT,",
    "    y: FLOAT,",
    "} ",
    "pub struct GLYPHMETRICSFLOAT {",
    "    gmfBlackBoxX: FLOAT,",
    "    gmfBlackBoxY: FLOAT,",
    "    gmfptGlyphOrigin: POINTFLOAT,",
    "    gmfCellIncX: FLOAT,",
    "    gmfCellIncY: FLOAT,",
    "}",
    "pub type LPGLYPHMETRICSFLOAT = *GLYPHMETRICSFLOAT;",
    "pub struct LAYERPLANEDESCRIPTOR {",
    "    nSize: WORD,",
    "    nVersion: WORD,",
    "    dwFlags: DWORD,",
    "    iPixelType: BYTE,",
    "    cColorBits: BYTE,",
    "    cRedBits: BYTE,",
    "    cRedShift: BYTE,",
    "    cGreenBits: BYTE,",
    "    cGreenShift: BYTE,",
    "    cBlueBits: BYTE,",
    "    cBlueShift: BYTE,",
    "    cAlphaBits: BYTE,",
    "    cAlphaShift: BYTE,",
    "    cAccumBits: BYTE,",
    "    cAccumRedBits: BYTE,",
    "    cAccumGreenBits: BYTE,",
    "    cAccumBlueBits: BYTE,",
    "    cAccumAlphaBits: BYTE,",
    "    cDepthBits: BYTE,",
    "    cStencilBits: BYTE,",
    "    cAuxBuffers: BYTE,",
    "    iLayerType: BYTE,",
    "    bReserved: BYTE,",
    "    crTransparent: COLORREF,",
    "}",
    "pub struct PIXELFORMATDESCRIPTOR {",
    "    nSize: WORD,",
    "    nVersion: WORD,",
    "    dwFlags: DWORD,",
    "    iPixelType: BYTE,",
    "    cColorBits: BYTE,",
    "    cRedBits: BYTE,",
    "    cRedShift: BYTE,",
    "    cGreenBits: BYTE,",
    "    cGreenShift: BYTE,",
    "    cBlueBits: BYTE,",
    "    cBlueShift: BYTE,",
    "    cAlphaBits: BYTE,",
    "    cAlphaShift: BYTE,",
    "    cAccumBits: BYTE,",
    "    cAccumRedBits: BYTE,",
    "    cAccumGreenBits: BYTE,",
    "    cAccumBlueBits: BYTE,",
    "    cAccumAlphaBits: BYTE,",
    "    cDepthBits: BYTE,",
    "    cStencilBits: BYTE,",
    "    cAuxBuffers: BYTE,",
    "    iLayerType: BYTE,",
    "    bReserved: BYTE,",
    "    dwLayerMask: DWORD,",
    "    dwVisibleMask: DWORD,",
    "    dwDamageMask: DWORD,",
    "}",
];

pub static WGL_ALIASES: Src = &[
    "// From WinNT.h",
    "// #define DECLARE_HANDLE(name) struct name##__{int unused;}; typedef struct name##__ *name",
    "macro_rules! DECLARE_HANDLE(",
    "    ($name:ident) => (",
    "        pub type $name = *c_void;",
    "    )",
    ")",
    "",
    "pub struct _GPU_DEVICE {",
    "    cb: DWORD,",
    "    DeviceName: [CHAR, ..32],",
    "    DeviceString: [CHAR, ..128],",
    "    Flags: DWORD,",
    "    rcVirtualScreen: RECT,",
    "}",
    "DECLARE_HANDLE!(HPBUFFERARB)",
    "DECLARE_HANDLE!(HPBUFFEREXT)",
    "DECLARE_HANDLE!(HVIDEOOUTPUTDEVICENV)",
    "DECLARE_HANDLE!(HPVIDEODEV)",
    "DECLARE_HANDLE!(HPGPUNV)",
    "DECLARE_HANDLE!(HGPUNV)",
    "DECLARE_HANDLE!(HVIDEOINPUTDEVICENV)",
    "pub struct GPU_DEVICE(_GPU_DEVICE);",
    "pub struct PGPU_DEVICE(*_GPU_DEVICE);",
];
